// <auto-generated />
using HomePet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomePet.Migrations
{
    [DbContext(typeof(PetDbContext))]
    [Migration("20190612000655_Arreglado")]
    partial class Arreglado
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HomePet.Models.Edad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NombreEdad");

                    b.HasKey("Id");

                    b.ToTable("MascotaEdad");
                });

            modelBuilder.Entity("HomePet.Models.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EdadId");

                    b.Property<string>("Foto");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<float>("Peso");

                    b.Property<string>("Sexo")
                        .IsRequired();

                    b.Property<int>("TamanoId");

                    b.Property<int>("TipoPeloId");

                    b.HasKey("Id");

                    b.HasIndex("EdadId");

                    b.HasIndex("TamanoId");

                    b.HasIndex("TipoPeloId");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("HomePet.Models.Tamano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NombreTamano");

                    b.HasKey("Id");

                    b.ToTable("MascotaTamano");
                });

            modelBuilder.Entity("HomePet.Models.TipoPelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NombreTipoPelo");

                    b.HasKey("Id");

                    b.ToTable("MascotaTipoPelo");
                });

            modelBuilder.Entity("HomePet.Models.Mascota", b =>
                {
                    b.HasOne("HomePet.Models.Edad", "Edad")
                        .WithMany("MascotaEdad")
                        .HasForeignKey("EdadId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HomePet.Models.Tamano", "Tamano")
                        .WithMany("MascotaTamano")
                        .HasForeignKey("TamanoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HomePet.Models.TipoPelo", "TipoPelo")
                        .WithMany("MascotaTipoPelo")
                        .HasForeignKey("TipoPeloId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
